"""initial_schema

Revision ID: fd27ddb4d4eb
Revises: 
Create Date: 2026-05-16 06:49:47.392626+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'fd27ddb4d4eb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FARMER', 'AGRONOMIST', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('preferred_language', sa.String(length=12), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('total_area_hectares', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('soil_type', sa.String(length=80), nullable=False),
    sa.Column('water_source', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_name'), 'farms', ['name'], unique=False)
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_table('marketplace_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('category', sa.Enum('SEEDS', 'FERTILIZER', 'EQUIPMENT', 'PRODUCE', 'SERVICE', name='marketplacecategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SOLD', 'ARCHIVED', name='marketplacestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_items_category'), 'marketplace_items', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_items_seller_id'), 'marketplace_items', ['seller_id'], unique=False)
    op.create_table('chatbot_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatrole'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_messages_farm_id'), 'chatbot_messages', ['farm_id'], unique=False)
    op.create_index(op.f('ix_chatbot_messages_role'), 'chatbot_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chatbot_messages_user_id'), 'chatbot_messages', ['user_id'], unique=False)
    op.create_table('drone_missions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('mission_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='missionstatus'), nullable=False),
    sa.Column('flight_path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('imagery_url', sa.String(length=500), nullable=True),
    sa.Column('ai_findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drone_missions_created_by_id'), 'drone_missions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_drone_missions_farm_id'), 'drone_missions', ['farm_id'], unique=False)
    op.create_table('farm_zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('crop_name', sa.String(length=120), nullable=False),
    sa.Column('area_hectares', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('irrigation_mode', sa.Enum('MANUAL', 'AUTOMATIC', 'SCHEDULED', name='irrigationmode'), nullable=False),
    sa.Column('moisture_min_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('moisture_max_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_zones_farm_id'), 'farm_zones', ['farm_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.Enum('SENSOR', 'IRRIGATION', 'WEATHER', 'AI', 'MARKETPLACE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='notificationchannel'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity'), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_farm_id'), 'notifications', ['farm_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('humidity', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rainfall_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('wind_speed', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('condition', sa.String(length=120), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_captured_at'), 'weather_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_farm_id'), 'weather_snapshots', ['farm_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('CROP', 'FERTILIZER', 'YIELD', 'IRRIGATION', 'WEATHER_RISK', name='recommendationtype'), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['farm_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_farm_id'), 'ai_recommendations', ['farm_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_recommendation_type'), 'ai_recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_user_id'), 'ai_recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_zone_id'), 'ai_recommendations', ['zone_id'], unique=False)
    op.create_table('crop_calendar_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('crop_name', sa.String(length=120), nullable=False),
    sa.Column('activity_type', sa.Enum('SOWING', 'IRRIGATION', 'FERTILIZING', 'SPRAYING', 'HARVESTING', 'INSPECTION', name='calendaractivitytype'), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', 'OVERDUE', name='calendarstatus'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['farm_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_calendar_events_activity_type'), 'crop_calendar_events', ['activity_type'], unique=False)
    op.create_index(op.f('ix_crop_calendar_events_farm_id'), 'crop_calendar_events', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crop_calendar_events_scheduled_for'), 'crop_calendar_events', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_crop_calendar_events_zone_id'), 'crop_calendar_events', ['zone_id'], unique=False)
    op.create_table('disease_detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('crop_name', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('disease_name', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('treatment_advice', sa.String(length=1000), nullable=False),
    sa.Column('prevention_advice', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['farm_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_detections_farm_id'), 'disease_detections', ['farm_id'], unique=False)
    op.create_index(op.f('ix_disease_detections_user_id'), 'disease_detections', ['user_id'], unique=False)
    op.create_index(op.f('ix_disease_detections_zone_id'), 'disease_detections', ['zone_id'], unique=False)
    op.create_table('irrigation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.Enum('MANUAL', 'AUTOMATIC', 'SCHEDULED', name='irrigationmode'), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'STOPPED', 'COMPLETED', 'FAILED', name='irrigationstatus'), nullable=False),
    sa.Column('water_used_liters', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['farm_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_events_farm_id'), 'irrigation_events', ['farm_id'], unique=False)
    op.create_index(op.f('ix_irrigation_events_triggered_by_id'), 'irrigation_events', ['triggered_by_id'], unique=False)
    op.create_index(op.f('ix_irrigation_events_zone_id'), 'irrigation_events', ['zone_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sensor_type', sa.Enum('SOIL_MOISTURE', 'TEMPERATURE', 'HUMIDITY', 'WATER_TANK', 'PH', 'NPK', 'LIGHT', 'MULTI', name='sensortype'), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'MAINTENANCE', 'FAULT', name='sensorstatus'), nullable=False),
    sa.Column('hardware_id', sa.String(length=120), nullable=False),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('battery_level', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('signal_strength', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['farm_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_farm_id'), 'sensors', ['farm_id'], unique=False)
    op.create_index(op.f('ix_sensors_hardware_id'), 'sensors', ['hardware_id'], unique=True)
    op.create_index(op.f('ix_sensors_zone_id'), 'sensors', ['zone_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('soil_moisture', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('water_tank_level', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ph_level', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('rainfall_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('nitrogen', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('phosphorus', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('potassium', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('light_intensity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['farm_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_farm_id'), 'sensor_readings', ['farm_id'], unique=False)
    op.create_index('ix_sensor_readings_farm_recorded_at', 'sensor_readings', ['farm_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index('ix_sensor_readings_sensor_recorded_at', 'sensor_readings', ['sensor_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_zone_id'), 'sensor_readings', ['zone_id'], unique=False)
    op.create_index('ix_sensor_readings_zone_recorded_at', 'sensor_readings', ['zone_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_readings_zone_recorded_at', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_zone_id'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_sensor_recorded_at', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_farm_recorded_at', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_farm_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sensors_zone_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_hardware_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_farm_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_irrigation_events_zone_id'), table_name='irrigation_events')
    op.drop_index(op.f('ix_irrigation_events_triggered_by_id'), table_name='irrigation_events')
    op.drop_index(op.f('ix_irrigation_events_farm_id'), table_name='irrigation_events')
    op.drop_table('irrigation_events')
    op.drop_index(op.f('ix_disease_detections_zone_id'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_user_id'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_farm_id'), table_name='disease_detections')
    op.drop_table('disease_detections')
    op.drop_index(op.f('ix_crop_calendar_events_zone_id'), table_name='crop_calendar_events')
    op.drop_index(op.f('ix_crop_calendar_events_scheduled_for'), table_name='crop_calendar_events')
    op.drop_index(op.f('ix_crop_calendar_events_farm_id'), table_name='crop_calendar_events')
    op.drop_index(op.f('ix_crop_calendar_events_activity_type'), table_name='crop_calendar_events')
    op.drop_table('crop_calendar_events')
    op.drop_index(op.f('ix_ai_recommendations_zone_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_user_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_recommendation_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_farm_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_weather_snapshots_farm_id'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_captured_at'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_farm_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_farm_zones_farm_id'), table_name='farm_zones')
    op.drop_table('farm_zones')
    op.drop_index(op.f('ix_drone_missions_farm_id'), table_name='drone_missions')
    op.drop_index(op.f('ix_drone_missions_created_by_id'), table_name='drone_missions')
    op.drop_table('drone_missions')
    op.drop_index(op.f('ix_chatbot_messages_user_id'), table_name='chatbot_messages')
    op.drop_index(op.f('ix_chatbot_messages_role'), table_name='chatbot_messages')
    op.drop_index(op.f('ix_chatbot_messages_farm_id'), table_name='chatbot_messages')
    op.drop_table('chatbot_messages')
    op.drop_index(op.f('ix_marketplace_items_seller_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_category'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_name'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
